### ISSUE TITLE
Making the App Look Good on Mobile

### ISSUE THREAD

**Issue by MarcoMorawec** [tbowyer/test#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by tbowyer** [comment]
I googled "mobile meta tag" and came across this page explaining how you need to add this to the top of your main .html page, which makes it so the viewport on your phone will change depending on your phone's screen size when viewing the app.  I just pushed it to heroku and now it looks scaled much better on my phone.  Does it look okay to you now?  https://splurty-trevor-bowyer.herokuapp.com/

**Comment by tbowyer** [comment]
https://css-tricks.com/snippets/html/responsive-meta-tag/

Was the page I found, I forgot to include a link.

**Comment by MarcoMorawec** [comment]
@tbowyer :+1:
